import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CreaturesService {

  creatures = [
    {
      "Name": " Nymph ",
      "Lvl": "1",
      "Att": "5",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "4",
      "Spd": "6",
      "Grw": "16",
      "Val": "57",
      "35 ": "45 ",
      "Special": "Teleporting, Immune to ice",
      "Town": "Cove",
      "Cost": "35"
    },
    {
      "Name": "Oceanid ",
      "Lvl": "1 up",
      "Att": "6",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "4",
      "Spd": "8",
      "Grw": "16",
      "Val": "75",
      "35 ": "110 ",
      "Special": "Teleporting, Immune to ice",
      "Town": "Cove",
      "Cost": "45 "
    },
    {
      "Name": " Crew Mate",
      "Lvl": "2",
      "Att": "7",
      "Def": "4",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "15",
      "Spd": "5",
      "Grw": "9",
      "Val": "155",
      "35 ": "140 ",
      "Town": "Cove",
      "Cost": "110 "
    },
    {
      "Name": " Seaman ",
      "Lvl": "2 up",
      "Att": "8",
      "Def": "6",
      "minDmg": "3",
      "maxDmg": "4",
      "HP": "15",
      "Spd": "6",
      "Grw": "9",
      "Val": "174",
      "35 ": "225 ",
      "Town": "Cove",
      "Cost": "140 "
    },
    {
      "Name": " Pirate ",
      "Lvl": "3",
      "Att": "8",
      "Def": "6",
      "minDmg": "3",
      "maxDmg": "7",
      "HP": "15",
      "Spd": "6",
      "Grw": "7",
      "Val": "312",
      "35 ": "275 ",
      "Special": "Ranged (4 shots)",
      "Town": "Cove",
      "Cost": "225 "
    },
    {
      "Name": " Corsair ",
      "Lvl": "3 up",
      "Att": "10",
      "Def": "8",
      "minDmg": "3",
      "maxDmg": "7",
      "HP": "15",
      "Spd": "7",
      "Grw": "7",
      "Val": "407",
      "35 ": "375 ",
      "Special": "Ranged (4 shots)",
      "Town": "Cove",
      "Cost": "275 "
    },
    {
      "Name": " Sea Dog ",
      "Lvl": "3 up",
      "Att": "12",
      "Def": "11",
      "minDmg": "3",
      "maxDmg": "7",
      "HP": "15",
      "Spd": "8",
      "Grw": "7",
      "Val": "602",
      "35 ": "275 ",
      "Special": "Ranged (12 shots), No melee penalty, No enemy retaliation, Accurate Shot",
      "Town": "Cove",
      "Cost": "375 "
    },
    {
      "Name": " Stormbird ",
      "Lvl": "4",
      "Att": "10",
      "Def": "8",
      "minDmg": "6",
      "maxDmg": "9",
      "HP": "30",
      "Spd": "9",
      "Grw": "4",
      "Val": "502",
      "35 ": "325 ",
      "Special": "Flying",
      "Town": "Cove",
      "Cost": "275 "
    },
    {
      "Name": " Ayssid ",
      "Lvl": "4 up",
      "Att": "11",
      "Def": "8",
      "minDmg": "6",
      "maxDmg": "10",
      "HP": "30",
      "Spd": "11",
      "Grw": "4",
      "Val": "645",
      "35 ": "515 ",
      "Special": "Flying, Ferocity",
      "Town": "Cove",
      "Cost": "325 "
    },
    {
      "Name": " Sea Witch ",
      "Lvl": "5",
      "Att": "12",
      "Def": "7",
      "minDmg": "10",
      "maxDmg": "14",
      "HP": "35",
      "Spd": "6",
      "Grw": "3",
      "Val": "790",
      "35 ": "565 ",
      "Special": "Ranged (12 shots), Casts Weakness / Disrupting Ray",
      "Town": "Cove",
      "Cost": "515 "
    },
    {
      "Name": " Sorceress ",
      "Lvl": "5 up",
      "Att": "12",
      "Def": "9",
      "minDmg": "10",
      "maxDmg": "16",
      "HP": "35",
      "Spd": "7",
      "Grw": "3",
      "Val": "852",
      "35 ": "1000 ",
      "Special": "Ranged (12 shots), Casts Weakness / Disrupting Ray",
      "Town": "Cove",
      "Cost": "565 "
    },
    {
      "Name": " Nix ",
      "Lvl": "6",
      "Att": "13",
      "Def": "16",
      "minDmg": "18",
      "maxDmg": "22",
      "HP": "80",
      "Spd": "6",
      "Grw": "2",
      "Val": "1415",
      "35 ": "1300 ",
      "Special": "Ignores 30% of enemy attack value",
      "Town": "Cove",
      "Cost": "1000 "
    },
    {
      "Name": " Nix Warrior ",
      "Lvl": "6 up",
      "Att": "14",
      "Def": "17",
      "minDmg": "18",
      "maxDmg": "22",
      "HP": "90",
      "Spd": "7",
      "Grw": "2",
      "Val": "2116",
      "35 ": "2200 ",
      "Special": "Ignores 60% of enemy attack value",
      "Town": "Cove",
      "Cost": "1300 "
    },
    {
      "Name": " Sea Serpent ",
      "Lvl": "7",
      "Att": "22",
      "Def": "16",
      "minDmg": "30",
      "maxDmg": "55",
      "HP": "180",
      "Spd": "9",
      "Grw": "1",
      "Val": "3953",
      "35 ": "4000 ",
      " Special": ", 1   ",
      "Special": "Poisonous",
      "Town": "Cove",
      "Cost": "2200 ",
      "SpecialCost": "s1 "
    },
    {
      "Name": " Haspid ",
      "Lvl": "7 up",
      "Att": "29",
      "Def": "20",
      "minDmg": "30",
      "maxDmg": "55",
      "HP": "300",
      "Spd": "12",
      "Grw": "1",
      "Val": "7220",
      "35 ": "60 ",
      " Special": ", 2   ",
      "Special": "Poisonous, Revenge",
      "Town": "Cove",
      "Cost": "4000 ",
      "SpecialCost": "s2 "
    },
    {
      "Name": " Pikeman ",
      "Lvl": "1",
      "Att": "4",
      "Def": "5",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "10",
      "Spd": "4",
      "Grw": "14",
      "Val": "80",
      "35 ": "75 ",
      "Special": "Immune to jousting",
      "Town": "Castle",
      "Cost": "60 "
    },
    {
      "Name": " Halberdier ",
      "Lvl": "1 up",
      "Att": "6",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "10",
      "Spd": "5",
      "Grw": "14",
      "Val": "115",
      "35 ": "100 ",
      "Special": "Immune to jousting",
      "Town": "Castle",
      "Cost": "75 "
    },
    {
      "Name": " Archer ",
      "Lvl": "2",
      "Att": "6",
      "Def": "3",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "10",
      "Spd": "4",
      "Grw": "9",
      "Val": "126",
      "35 ": "150 ",
      "Special": "Ranged (12 shots)",
      "Town": "Castle",
      "Cost": "100 "
    },
    {
      "Name": " Marksman ",
      "Lvl": "2 up",
      "Att": "6",
      "Def": "3",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "10",
      "Spd": "6",
      "Grw": "9",
      "Val": "184",
      "35 ": "200 ",
      "Special": "Ranged (24 shots), Double attack",
      "Town": "Castle",
      "Cost": "150 "
    },
    {
      "Name": " Griffin ",
      "Lvl": "3",
      "Att": "8",
      "Def": "8",
      "minDmg": "3",
      "maxDmg": "6",
      "HP": "25",
      "Spd": "6",
      "Grw": "7",
      "Val": "351",
      "35 ": "240 ",
      "Special": "Flying, Two retaliations",
      "Town": "Castle",
      "Cost": "200 "
    },
    {
      "Name": " Royal Griffin ",
      "Lvl": "3 up",
      "Att": "9",
      "Def": "9",
      "minDmg": "3",
      "maxDmg": "6",
      "HP": "25",
      "Spd": "9",
      "Grw": "7",
      "Val": "448",
      "35 ": "300 ",
      "Special": "Flying, Unlimited retaliations",
      "Town": "Castle",
      "Cost": "240 "
    },
    {
      "Name": " Swordsman ",
      "Lvl": "4",
      "Att": "10",
      "Def": "12",
      "minDmg": "6",
      "maxDmg": "9",
      "HP": "35",
      "Spd": "5",
      "Grw": "4",
      "Val": "445",
      "35 ": "400 ",
      "Town": "Castle",
      "Cost": "300 "
    },
    {
      "Name": " Crusader ",
      "Lvl": "4 up",
      "Att": "12",
      "Def": "12",
      "minDmg": "7",
      "maxDmg": "10",
      "HP": "35",
      "Spd": "6",
      "Grw": "4",
      "Val": "588",
      "35 ": "400 ",
      "Special": "Double attack",
      "Town": "Castle",
      "Cost": "400 "
    },
    {
      "Name": " Monk ",
      "Lvl": "5",
      "Att": "12",
      "Def": "7",
      "minDmg": "10",
      "maxDmg": "12",
      "HP": "30",
      "Spd": "5",
      "Grw": "3",
      "Val": "582",
      "35 ": "450 ",
      "Special": "Ranged (12 shots)",
      "Town": "Castle",
      "Cost": "400 "
    },
    {
      "Name": " Zealot ",
      "Lvl": "5 up",
      "Att": "12",
      "Def": "10",
      "minDmg": "10",
      "maxDmg": "12",
      "HP": "30",
      "Spd": "7",
      "Grw": "3",
      "Val": "750",
      "35 ": "1000 ",
      "Special": "Ranged (24 shots), No melee penalty",
      "Town": "Castle",
      "Cost": "450 "
    },
    {
      "Name": " Cavalier ",
      "Lvl": "6",
      "Att": "15",
      "Def": "15",
      "minDmg": "15",
      "maxDmg": "25",
      "HP": "100",
      "Spd": "7",
      "Grw": "2",
      "Val": "1946",
      "35 ": "1200 ",
      "Special": "Jousting",
      "Town": "Castle",
      "Cost": "1000 "
    },
    {
      "Name": " Champion ",
      "Lvl": "6 up",
      "Att": "16",
      "Def": "16",
      "minDmg": "20",
      "maxDmg": "25",
      "HP": "100",
      "Spd": "9",
      "Grw": "2",
      "Val": "2100",
      "35 ": "3000 ",
      "Special": "Jousting",
      "Town": "Castle",
      "Cost": "1200 "
    },
    {
      "Name": " Angel ",
      "Lvl": "7",
      "Att": "20",
      "Def": "20",
      "minDmg": "50",
      "maxDmg": "50",
      "HP": "200",
      "Spd": "12",
      "Grw": "1",
      "Val": "5019",
      "35 ": "5000 ",
      " Special": ", 1  ",
      "Special": "Flying, Hates Devils, Morale +1",
      "Town": "Castle",
      "Cost": "3000 ",
      "SpecialCost": "g1 "
    },
    {
      "Name": " Archangel ",
      "Lvl": "7 up",
      "Att": "30",
      "Def": "30",
      "minDmg": "50",
      "maxDmg": "50",
      "HP": "250",
      "Spd": "18",
      "Grw": "1",
      "Val": "8776",
      "35 ": "70 ",
      " Special": ", 3  ",
      "Special": "Flying, Hates Devils, Resurrection, Morale +1",
      "Town": "Castle",
      "Cost": "5000 ",
      "SpecialCost": "g3"
    },
    {
      "Name": " Centaur ",
      "Lvl": "1",
      "Att": "5",
      "Def": "3",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "8",
      "Spd": "6",
      "Grw": "14",
      "Val": "100",
      "35 ": "90 ",
      "Town": "Rampart",
      "Cost": "70 "
    },
    {
      "Name": " Centaur Captain ",
      "Lvl": "1 up",
      "Att": "6",
      "Def": "3",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "10",
      "Spd": "8",
      "Grw": "14",
      "Val": "138",
      "35 ": "120 ",
      "Town": "Rampart",
      "Cost": "90 "
    },
    {
      "Name": " Dwarf ",
      "Lvl": "2",
      "Att": "6",
      "Def": "7",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "20",
      "Spd": "3",
      "Grw": "8",
      "Val": "138",
      "35 ": "150 ",
      "Special": "Resistance +20%",
      "Town": "Rampart",
      "Cost": "120 "
    },
    {
      "Name": " Battle Dwarf ",
      "Lvl": "2 up",
      "Att": "7",
      "Def": "7",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "20",
      "Spd": "5",
      "Grw": "8",
      "Val": "209",
      "35 ": "200 ",
      "Special": "Resistance +40%",
      "Town": "Rampart",
      "Cost": "150 "
    },
    {
      "Name": " Wood Elf ",
      "Lvl": "3",
      "Att": "9",
      "Def": "5",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "15",
      "Spd": "6",
      "Grw": "7",
      "Val": "234",
      "35 ": "225 ",
      "Special": "Ranged (24 shots)",
      "Town": "Rampart",
      "Cost": "200 "
    },
    {
      "Name": " Grand Elf ",
      "Lvl": "3 up",
      "Att": "9",
      "Def": "5",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "15",
      "Spd": "7",
      "Grw": "7",
      "Val": "331",
      "35 ": "250 ",
      "Special": "Ranged (24 shots), Double attack",
      "Town": "Rampart",
      "Cost": "225 "
    },
    {
      "Name": " Pegasus ",
      "Lvl": "4",
      "Att": "9",
      "Def": "8",
      "minDmg": "5",
      "maxDmg": "9",
      "HP": "30",
      "Spd": "8",
      "Grw": "5",
      "Val": "518",
      "35 ": "275 ",
      "Special": "Flying, Magic damper",
      "Town": "Rampart",
      "Cost": "250 "
    },
    {
      "Name": " Silver Pegasus ",
      "Lvl": "4 up",
      "Att": "9",
      "Def": "10",
      "minDmg": "5",
      "maxDmg": "9",
      "HP": "30",
      "Spd": "12",
      "Grw": "5",
      "Val": "532",
      "35 ": "350 ",
      "Special": "Flying, Magic damper",
      "Town": "Rampart",
      "Cost": "275 "
    },
    {
      "Name": " Dendroid Guard ",
      "Lvl": "5",
      "Att": "9",
      "Def": "12",
      "minDmg": "10",
      "maxDmg": "14",
      "HP": "55",
      "Spd": "3",
      "Grw": "3",
      "Val": "517",
      "35 ": "425 ",
      "Special": "Binding",
      "Town": "Rampart",
      "Cost": "350 "
    },
    {
      "Name": " Dendroid Soldier ",
      "Lvl": "5 up",
      "Att": "9",
      "Def": "12",
      "minDmg": "10",
      "maxDmg": "14",
      "HP": "65",
      "Spd": "4",
      "Grw": "3",
      "Val": "803",
      "35 ": "850 ",
      "Special": "Binding",
      "Town": "Rampart",
      "Cost": "425 "
    },
    {
      "Name": " Unicorn ",
      "Lvl": "6",
      "Att": "15",
      "Def": "14",
      "minDmg": "18",
      "maxDmg": "22",
      "HP": "90",
      "Spd": "7",
      "Grw": "2",
      "Val": "1806",
      "35 ": "950 ",
      "Special": "Blind, Aura of Resistance+20%",
      "Town": "Rampart",
      "Cost": "850 "
    },
    {
      "Name": " War Unicorn ",
      "Lvl": "6 up",
      "Att": "15",
      "Def": "14",
      "minDmg": "18",
      "maxDmg": "22",
      "HP": "110",
      "Spd": "9",
      "Grw": "2",
      "Val": "2030",
      "35 ": "2400 ",
      "Special": "Blind, Aura of Resistance+20%",
      "Town": "Rampart",
      "Cost": "950 "
    },
    {
      "Name": " Green Dragon ",
      "Lvl": "7",
      "Att": "18",
      "Def": "18",
      "minDmg": "40",
      "maxDmg": "50",
      "HP": "180",
      "Spd": "10",
      "Grw": "1",
      "Val": "4872",
      "35 ": "4000 ",
      " Special": ", 1  ",
      "Special": "Flying, Breath attack, Resist lvl 1–3 spells",
      "Town": "Rampart",
      "Cost": "2400 ",
      "SpecialCost": "k1 "
    },
    {
      "Name": " Gold Dragon ",
      "Lvl": "7 up",
      "Att": "27",
      "Def": "27",
      "minDmg": "40",
      "maxDmg": "50",
      "HP": "250",
      "Spd": "16",
      "Grw": "1",
      "Val": "8613",
      "35 ": "30 ",
      " Special": ", 2  ",
      "Special": "Flying, Breath attack, Resist lvl 1–4 spells",
      "Town": "Rampart",
      "Cost": "4000 ",
      "SpecialCost": "k2"
    },
    {
      "Name": " Gremlin ",
      "Lvl": "1",
      "Att": "3",
      "Def": "3",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "4",
      "Spd": "4",
      "Grw": "16",
      "Val": "44",
      "35 ": "40 ",
      "Town": "Tower",
      "Cost": "30 "
    },
    {
      "Name": " Master Gremlin ",
      "Lvl": "1 up",
      "Att": "4",
      "Def": "4",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "4",
      "Spd": "5",
      "Grw": "16",
      "Val": "66",
      "35 ": "130 ",
      "Special": "Ranged (8 shots)",
      "Town": "Tower",
      "Cost": "40 "
    },
    {
      "Name": " Stone Gargoyle ",
      "Lvl": "2",
      "Att": "6",
      "Def": "6",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "16",
      "Spd": "6",
      "Grw": "9",
      "Val": "165",
      "35 ": "160 ",
      "Special": "Unliving, Flying",
      "Town": "Tower",
      "Cost": "130 "
    },
    {
      "Name": " Obsidian Gargoyle ",
      "Lvl": "2 up",
      "Att": "7",
      "Def": "7",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "16",
      "Spd": "9",
      "Grw": "9",
      "Val": "201",
      "35 ": "150 ",
      "Special": "Unliving, Flying",
      "Town": "Tower",
      "Cost": "160 "
    },
    {
      "Name": " Stone Golem ",
      "Lvl": "3",
      "Att": "7",
      "Def": "10",
      "minDmg": "4",
      "maxDmg": "5",
      "HP": "30",
      "Spd": "3",
      "Grw": "6",
      "Val": "250",
      "35 ": "200 ",
      "Special": "Unliving, Spell Damage Resistance +50%",
      "Town": "Tower",
      "Cost": "150 "
    },
    {
      "Name": " Iron Golem ",
      "Lvl": "3 up",
      "Att": "9",
      "Def": "10",
      "minDmg": "4",
      "maxDmg": "5",
      "HP": "35",
      "Spd": "5",
      "Grw": "6",
      "Val": "412",
      "35 ": "350 ",
      "Special": "Unliving, Spell Damage Resistance +75%",
      "Town": "Tower",
      "Cost": "200 "
    },
    {
      "Name": " Mage ",
      "Lvl": "4",
      "Att": "11",
      "Def": "8",
      "minDmg": "7",
      "maxDmg": "9",
      "HP": "25",
      "Spd": "5",
      "Grw": "4",
      "Val": "570",
      "35 ": "450 ",
      "Special": "Ranged (24 shots), No melee penalty, Spells cost -2 sp",
      "Town": "Tower",
      "Cost": "350 "
    },
    {
      "Name": " Arch Mage ",
      "Lvl": "4 up",
      "Att": "12",
      "Def": "9",
      "minDmg": "7",
      "maxDmg": "9",
      "HP": "30",
      "Spd": "7",
      "Grw": "4",
      "Val": "680",
      "35 ": "550 ",
      "Special": "Ranged (24 shots), No melee penalty, No obstacle penalty, Spells cost -2 sp",
      "Town": "Tower",
      "Cost": "450 "
    },
    {
      "Name": " Genie ",
      "Lvl": "5",
      "Att": "12",
      "Def": "12",
      "minDmg": "13",
      "maxDmg": "16",
      "HP": "40",
      "Spd": "7",
      "Grw": "3",
      "Val": "884",
      "35 ": "600 ",
      "Special": "Flying, Hates Efreets",
      "Town": "Tower",
      "Cost": "550 "
    },
    {
      "Name": " Master Genie ",
      "Lvl": "5 up",
      "Att": "12",
      "Def": "12",
      "minDmg": "13",
      "maxDmg": "16",
      "HP": "40",
      "Spd": "11",
      "Grw": "3",
      "Val": "942",
      "35 ": "1100 ",
      "Special": "Flying, Spellcaster, HatesEfreets",
      "Town": "Tower",
      "Cost": "600 "
    },
    {
      "Name": " Naga ",
      "Lvl": "6",
      "Att": "16",
      "Def": "13",
      "minDmg": "20",
      "maxDmg": "20",
      "HP": "110",
      "Spd": "5",
      "Grw": "2",
      "Val": "2016",
      "35 ": "1600 ",
      "Special": "No enemy retaliation",
      "Town": "Tower",
      "Cost": "1100 "
    },
    {
      "Name": " Naga Queen ",
      "Lvl": "6 up",
      "Att": "16",
      "Def": "13",
      "minDmg": "30",
      "maxDmg": "30",
      "HP": "110",
      "Spd": "7",
      "Grw": "2",
      "Val": "2840",
      "35 ": "2000 ",
      "Special": "No enemy retaliation",
      "Town": "Tower",
      "Cost": "1600 "
    },
    {
      "Name": " Giant ",
      "Lvl": "7",
      "Att": "19",
      "Def": "16",
      "minDmg": "40",
      "maxDmg": "60",
      "HP": "150",
      "Spd": "7",
      "Grw": "1",
      "Val": "3718",
      "35 ": "5000 ",
      " Special": ", 1  ",
      "Special": "Immunity to Mind",
      "Town": "Tower",
      "Cost": "2000 ",
      "SpecialCost": "g1 "
    },
    {
      "Name": " Titan ",
      "Lvl": "7 up",
      "Att": "24",
      "Def": "24",
      "minDmg": "40",
      "maxDmg": "60",
      "HP": "300",
      "Spd": "11",
      "Grw": "1",
      "Val": "7500",
      "35 ": "50 ",
      " Special": ", 2  ",
      "Special": "Ranged (24 shots), No melee penalty, Immunity to Mind, Hates Black Dragons",
      "Town": "Tower",
      "Cost": "5000 ",
      "SpecialCost": "g2"
    },
    {
      "Name": " Imp ",
      "Lvl": "1",
      "Att": "2",
      "Def": "3",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "4",
      "Spd": "5",
      "Grw": "15",
      "Val": "50",
      "35 ": "60 ",
      "Town": "Inferno",
      "Cost": "50 "
    },
    {
      "Name": " Familiar ",
      "Lvl": "1 up",
      "Att": "4",
      "Def": "4",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "4",
      "Spd": "7",
      "Grw": "15",
      "Val": "60",
      "35 ": "125 ",
      "Special": "Magic channel",
      "Town": "Inferno",
      "Cost": "60 "
    },
    {
      "Name": " Gog ",
      "Lvl": "2",
      "Att": "6",
      "Def": "4",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "13",
      "Spd": "4",
      "Grw": "8",
      "Val": "159",
      "35 ": "175 ",
      "Special": "Ranged (12 shots)",
      "Town": "Inferno",
      "Cost": "125 "
    },
    {
      "Name": " Magog ",
      "Lvl": "2 up",
      "Att": "7",
      "Def": "4",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "13",
      "Spd": "6",
      "Grw": "8",
      "Val": "240",
      "35 ": "200 ",
      "Special": "Ranged (24 shots), Fireball attack",
      "Town": "Inferno",
      "Cost": "175 "
    },
    {
      "Name": " Hell Hound ",
      "Lvl": "3",
      "Att": "10",
      "Def": "6",
      "minDmg": "2",
      "maxDmg": "7",
      "HP": "25",
      "Spd": "7",
      "Grw": "5",
      "Val": "357",
      "35 ": "250 ",
      "Town": "Inferno",
      "Cost": "200 "
    },
    {
      "Name": " Cerberus ",
      "Lvl": "3 up",
      "Att": "10",
      "Def": "8",
      "minDmg": "2",
      "maxDmg": "7",
      "HP": "25",
      "Spd": "8",
      "Grw": "5",
      "Val": "392",
      "35 ": "250 ",
      "Special": "No enemy retaliation, 3-headed attack",
      "Town": "Inferno",
      "Cost": "250 "
    },
    {
      "Name": " Demon ",
      "Lvl": "4",
      "Att": "10",
      "Def": "10",
      "minDmg": "7",
      "maxDmg": "9",
      "HP": "35",
      "Spd": "5",
      "Grw": "4",
      "Val": "445",
      "35 ": "270 ",
      "Town": "Inferno",
      "Cost": "250 "
    },
    {
      "Name": " Horned Demon ",
      "Lvl": "4 up",
      "Att": "10",
      "Def": "10",
      "minDmg": "7",
      "maxDmg": "9",
      "HP": "40",
      "Spd": "6",
      "Grw": "4",
      "Val": "480",
      "35 ": "500 ",
      "Town": "Inferno",
      "Cost": "270 "
    },
    {
      "Name": " Pit Fiend ",
      "Lvl": "5",
      "Att": "13",
      "Def": "13",
      "minDmg": "13",
      "maxDmg": "17",
      "HP": "45",
      "Spd": "6",
      "Grw": "3",
      "Val": "765",
      "35 ": "700 ",
      "Town": "Inferno",
      "Cost": "500 "
    },
    {
      "Name": " Pit Lord ",
      "Lvl": "5 up",
      "Att": "13",
      "Def": "13",
      "minDmg": "13",
      "maxDmg": "17",
      "HP": "45",
      "Spd": "7",
      "Grw": "3",
      "Val": "1224",
      "35 ": "900 ",
      "Special": "Summon demons",
      "Town": "Inferno",
      "Cost": "700 "
    },
    {
      "Name": " Efreet ",
      "Lvl": "6",
      "Att": "16",
      "Def": "12",
      "minDmg": "16",
      "maxDmg": "24",
      "HP": "90",
      "Spd": "9",
      "Grw": "2",
      "Val": "1670",
      "35 ": "1100 ",
      "Special": "Flying, Fire immunity",
      "Town": "Inferno",
      "Cost": "900 "
    },
    {
      "Name": " Efreet Sultan ",
      "Lvl": "6 up",
      "Att": "16",
      "Def": "14",
      "minDmg": "16",
      "maxDmg": "24",
      "HP": "90",
      "Spd": "13",
      "Grw": "2",
      "Val": "2343",
      "35 ": "2700 ",
      "Special": "Flying, Fire shield, Fireimmunity, Hates Genies",
      "Town": "Inferno",
      "Cost": "1100 "
    },
    {
      "Name": " Devil ",
      "Lvl": "7",
      "Att": "19",
      "Def": "21",
      "minDmg": "30",
      "maxDmg": "40",
      "HP": "160",
      "Spd": "11",
      "Grw": "1",
      "Val": "5101",
      "35 ": "4500 ",
      " Special": ", 1  ",
      "Special": "Teleporting, No enemy retaliation, Luck -1, HatesAngels",
      "Town": "Inferno",
      "Cost": "2700 ",
      "SpecialCost": "m1 "
    },
    {
      "Name": " Arch Devil ",
      "Lvl": "7 up",
      "Att": "26",
      "Def": "28",
      "minDmg": "30",
      "maxDmg": "40",
      "HP": "200",
      "Spd": "17",
      "Grw": "1",
      "Val": "7115",
      "35 ": "60 ",
      " Special": ", 2  ",
      "Special": "Teleporting, No enemy retaliation, Luck -2, HatesAngels",
      "Town": "Inferno",
      "Cost": "4500 ",
      "SpecialCost": "m2"
    },
    {
      "Name": " Skeleton ",
      "Lvl": "1",
      "Att": "5",
      "Def": "4",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "6",
      "Spd": "4",
      "Grw": "12",
      "Val": "60",
      "35 ": "70 ",
      "Special": "Undead",
      "Town": "Necropolis",
      "Cost": "60 "
    },
    {
      "Name": " Skeleton Warrior ",
      "Lvl": "1 up",
      "Att": "6",
      "Def": "6",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "6",
      "Spd": "5",
      "Grw": "12",
      "Val": "85",
      "35 ": "100 ",
      "Special": "Undead",
      "Town": "Necropolis",
      "Cost": "70 "
    },
    {
      "Name": " Walking Dead ",
      "Lvl": "2",
      "Att": "5",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "15",
      "Spd": "3",
      "Grw": "8",
      "Val": "98",
      "35 ": "125 ",
      "Special": "Undead",
      "Town": "Necropolis",
      "Cost": "100 "
    },
    {
      "Name": " Zombie ",
      "Lvl": "2 up",
      "Att": "5",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "20",
      "Spd": "4",
      "Grw": "8",
      "Val": "128",
      "35 ": "200 ",
      "Special": "Undead, Disease",
      "Town": "Necropolis",
      "Cost": "125 "
    },
    {
      "Name": " Wight ",
      "Lvl": "3",
      "Att": "7",
      "Def": "7",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "18",
      "Spd": "5",
      "Grw": "7",
      "Val": "252",
      "35 ": "230 ",
      "Special": "Undead, Flying, Regeneration",
      "Town": "Necropolis",
      "Cost": "200 "
    },
    {
      "Name": " Wraith ",
      "Lvl": "3 up",
      "Att": "7",
      "Def": "7",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "18",
      "Spd": "7",
      "Grw": "7",
      "Val": "315",
      "35 ": "360 ",
      "Special": "Undead, Flying, Regeneration, Mana drain",
      "Town": "Necropolis",
      "Cost": "230 "
    },
    {
      "Name": " Vampire ",
      "Lvl": "4",
      "Att": "10",
      "Def": "9",
      "minDmg": "5",
      "maxDmg": "8",
      "HP": "30",
      "Spd": "6",
      "Grw": "4",
      "Val": "555",
      "35 ": "500 ",
      "Special": "Undead, Flying, No retaliation",
      "Town": "Necropolis",
      "Cost": "360 "
    },
    {
      "Name": " Vampire Lord ",
      "Lvl": "4 up",
      "Att": "10",
      "Def": "10",
      "minDmg": "5",
      "maxDmg": "8",
      "HP": "40",
      "Spd": "9",
      "Grw": "4",
      "Val": "783",
      "35 ": "550 ",
      "Special": "Undead, Flying, No retaliation, Life drain",
      "Town": "Necropolis",
      "Cost": "500 "
    },
    {
      "Name": " Lich ",
      "Lvl": "5",
      "Att": "13",
      "Def": "10",
      "minDmg": "11",
      "maxDmg": "13",
      "HP": "30",
      "Spd": "6",
      "Grw": "3",
      "Val": "848",
      "35 ": "600 ",
      "Special": "Ranged (12 shots), Undead, Death cloud",
      "Town": "Necropolis",
      "Cost": "550 "
    },
    {
      "Name": " Power Lich ",
      "Lvl": "5 up",
      "Att": "13",
      "Def": "10",
      "minDmg": "11",
      "maxDmg": "15",
      "HP": "40",
      "Spd": "7",
      "Grw": "3",
      "Val": "1079",
      "35 ": "1200 ",
      "Special": "Ranged (24 shots), Undead, Death cloud",
      "Town": "Necropolis",
      "Cost": "600 "
    },
    {
      "Name": " Black Knight ",
      "Lvl": "6",
      "Att": "16",
      "Def": "16",
      "minDmg": "15",
      "maxDmg": "30",
      "HP": "120",
      "Spd": "7",
      "Grw": "2",
      "Val": "2087",
      "35 ": "1500 ",
      "Special": "Undead, Curse",
      "Town": "Necropolis",
      "Cost": "1200 "
    },
    {
      "Name": " Dread Knight ",
      "Lvl": "6 up",
      "Att": "18",
      "Def": "18",
      "minDmg": "15",
      "maxDmg": "30",
      "HP": "120",
      "Spd": "9",
      "Grw": "2",
      "Val": "2382",
      "35 ": "1800 ",
      "Special": "Undead, Curse, Death blow",
      "Town": "Necropolis",
      "Cost": "1500 "
    },
    {
      "Name": " Bone Dragon ",
      "Lvl": "7",
      "Att": "17",
      "Def": "15",
      "minDmg": "25",
      "maxDmg": "50",
      "HP": "150",
      "Spd": "9",
      "Grw": "1",
      "Val": "3388",
      "35 ": "3000 ",
      "Special": "Dragon, Undead, Flying, Morale -1",
      "Town": "Necropolis",
      "Cost": "1800 "
    },
    {
      "Name": " Ghost Dragon ",
      "Lvl": "7 up",
      "Att": "19",
      "Def": "17",
      "minDmg": "25",
      "maxDmg": "50",
      "HP": "200",
      "Spd": "14",
      "Grw": "1",
      "Val": "4696",
      "35 ": "50 ",
      " Special": ", 1  ",
      "Special": "Dragon, Undead, Flying, Morale -1, Aging",
      "Town": "Necropolis",
      "Cost": "3000 ",
      "SpecialCost": "m1 "
    },
    {
      "Name": " Troglodyte ",
      "Lvl": "1",
      "Att": "4",
      "Def": "3",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "5",
      "Spd": "4",
      "Grw": "14",
      "Val": "59",
      "35 ": "65 ",
      "Special": "Immune to Blinding",
      "Town": "Dungeon",
      "Cost": "50 "
    },
    {
      "Name": " Infernal Troglodyte",
      "Lvl": "1 up",
      "Att": "5",
      "Def": "4",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "6",
      "Spd": "5",
      "Grw": "14",
      "Val": "84",
      "35 ": "130 ",
      "Special": "Immune to Blinding",
      "Town": "Dungeon",
      "Cost": "65 "
    },
    {
      "Name": " Harpy ",
      "Lvl": "2",
      "Att": "6",
      "Def": "5",
      "minDmg": "1",
      "maxDmg": "4",
      "HP": "14",
      "Spd": "6",
      "Grw": "8",
      "Val": "154",
      "35 ": "170 ",
      "Special": "Flying, Strike and return",
      "Town": "Dungeon",
      "Cost": "130 "
    },
    {
      "Name": " Harpy Hag ",
      "Lvl": "2 up",
      "Att": "6",
      "Def": "6",
      "minDmg": "1",
      "maxDmg": "4",
      "HP": "14",
      "Spd": "9",
      "Grw": "8",
      "Val": "238",
      "35 ": "250 ",
      "Special": "Flying, Strike and return, No enemy retaliation",
      "Town": "Dungeon",
      "Cost": "170 "
    },
    {
      "Name": " Beholder ",
      "Lvl": "3",
      "Att": "9",
      "Def": "7",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "22",
      "Spd": "5",
      "Grw": "7",
      "Val": "336",
      "35 ": "280 ",
      "Special": "Ranged (12 shots), No melee penalty",
      "Town": "Dungeon",
      "Cost": "250 "
    },
    {
      "Name": " Evil Eye ",
      "Lvl": "3 up",
      "Att": "10",
      "Def": "8",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "22",
      "Spd": "7",
      "Grw": "7",
      "Val": "367",
      "35 ": "300 ",
      "Special": "Ranged (24 shots), No melee penalty",
      "Town": "Dungeon",
      "Cost": "280 "
    },
    {
      "Name": " Medusa ",
      "Lvl": "4",
      "Att": "9",
      "Def": "9",
      "minDmg": "6",
      "maxDmg": "8",
      "HP": "25",
      "Spd": "5",
      "Grw": "4",
      "Val": "517",
      "35 ": "330 ",
      "Special": "Ranged (4 shots), No melee penalty, Petrify",
      "Town": "Dungeon",
      "Cost": "300 "
    },
    {
      "Name": " Medusa Queen ",
      "Lvl": "4 up",
      "Att": "10",
      "Def": "10",
      "minDmg": "6",
      "maxDmg": "8",
      "HP": "30",
      "Spd": "6",
      "Grw": "4",
      "Val": "577",
      "35 ": "500 ",
      "Special": "Ranged (8 shots), No melee penalty, Petrify",
      "Town": "Dungeon",
      "Cost": "330 "
    },
    {
      "Name": " Minotaur ",
      "Lvl": "5",
      "Att": "14",
      "Def": "12",
      "minDmg": "12",
      "maxDmg": "20",
      "HP": "50",
      "Spd": "6",
      "Grw": "3",
      "Val": "835",
      "35 ": "575 ",
      "Special": "Positive Morale",
      "Town": "Dungeon",
      "Cost": "500 "
    },
    {
      "Name": " Minotaur King ",
      "Lvl": "5 up",
      "Att": "15",
      "Def": "15",
      "minDmg": "12",
      "maxDmg": "20",
      "HP": "50",
      "Spd": "8",
      "Grw": "3",
      "Val": "1068",
      "35 ": "850 ",
      "Special": "Positive Morale",
      "Town": "Dungeon",
      "Cost": "575 "
    },
    {
      "Name": " Manticore ",
      "Lvl": "6",
      "Att": "15",
      "Def": "13",
      "minDmg": "14",
      "maxDmg": "20",
      "HP": "80",
      "Spd": "7",
      "Grw": "2",
      "Val": "1547",
      "35 ": "1050 ",
      "Special": "Flying",
      "Town": "Dungeon",
      "Cost": "850 "
    },
    {
      "Name": " Scorpicore ",
      "Lvl": "6 up",
      "Att": "16",
      "Def": "14",
      "minDmg": "14",
      "maxDmg": "20",
      "HP": "80",
      "Spd": "11",
      "Grw": "2",
      "Val": "1589",
      "35 ": "2500 ",
      "Special": "Flying, Paralyze",
      "Town": "Dungeon",
      "Cost": "1050 "
    },
    {
      "Name": " Red Dragon ",
      "Lvl": "7",
      "Att": "19",
      "Def": "19",
      "minDmg": "40",
      "maxDmg": "50",
      "HP": "180",
      "Spd": "11",
      "Grw": "1",
      "Val": "4702",
      "35 ": "4000 ",
      " Special": ", 1  ",
      "Special": "Dragon, Flying, Breath attack, 1-3 lvl spells immunity",
      "Town": "Dungeon",
      "Cost": "2500 ",
      "SpecialCost": "s1 "
    },
    {
      "Name": " Black Dragon ",
      "Lvl": "7 up",
      "Att": "25",
      "Def": "25",
      "minDmg": "40",
      "maxDmg": "50",
      "HP": "300",
      "Spd": "15",
      "Grw": "1",
      "Val": "8721",
      "35 ": "40 ",
      " Special": ", 2  ",
      "Special": "Dragon, Flying, Breath attack, Magic immunity, Hates Titans",
      "Town": "Dungeon",
      "Cost": "4000 ",
      "SpecialCost": "s2 "
    },
    {
      "Name": " Goblin ",
      "Lvl": "1",
      "Att": "4",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "5",
      "Spd": "5",
      "Grw": "15",
      "Val": "60",
      "35 ": "50 ",
      "Town": "Stronghold",
      "Cost": "40 "
    },
    {
      "Name": " Hobgoblin ",
      "Lvl": "1 up",
      "Att": "5",
      "Def": "3",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "5",
      "Spd": "7",
      "Grw": "15",
      "Val": "78",
      "35 ": "100 ",
      "Town": "Stronghold",
      "Cost": "50 "
    },
    {
      "Name": " Wolf Rider ",
      "Lvl": "2",
      "Att": "7",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "10",
      "Spd": "6",
      "Grw": "9",
      "Val": "130",
      "35 ": "140 ",
      "Town": "Stronghold",
      "Cost": "100 "
    },
    {
      "Name": " Wolf Raider ",
      "Lvl": "2 up",
      "Att": "8",
      "Def": "5",
      "minDmg": "3",
      "maxDmg": "4",
      "HP": "10",
      "Spd": "8",
      "Grw": "9",
      "Val": "203",
      "35 ": "150 ",
      "Special": "Double attack",
      "Town": "Stronghold",
      "Cost": "140 "
    },
    {
      "Name": " Orc ",
      "Lvl": "3",
      "Att": "8",
      "Def": "4",
      "minDmg": "2",
      "maxDmg": "5",
      "HP": "15",
      "Spd": "4",
      "Grw": "7",
      "Val": "192",
      "35 ": "165 ",
      "Special": "Ranged (12 shots)",
      "Town": "Stronghold",
      "Cost": "150 "
    },
    {
      "Name": " Orc Chieftain ",
      "Lvl": "3 up",
      "Att": "8",
      "Def": "4",
      "minDmg": "2",
      "maxDmg": "5",
      "HP": "20",
      "Spd": "5",
      "Grw": "7",
      "Val": "240",
      "35 ": "300 ",
      "Special": "Ranged (24 shots)",
      "Town": "Stronghold",
      "Cost": "165 "
    },
    {
      "Name": " Ogre ",
      "Lvl": "4",
      "Att": "13",
      "Def": "7",
      "minDmg": "6",
      "maxDmg": "12",
      "HP": "40",
      "Spd": "4",
      "Grw": "4",
      "Val": "416",
      "35 ": "400 ",
      "Town": "Stronghold",
      "Cost": "300 "
    },
    {
      "Name": " Ogre Mage ",
      "Lvl": "4 up",
      "Att": "13",
      "Def": "7",
      "minDmg": "6",
      "maxDmg": "12",
      "HP": "60",
      "Spd": "5",
      "Grw": "4",
      "Val": "672",
      "35 ": "600 ",
      "Special": "Cast Bloodlust x3",
      "Town": "Stronghold",
      "Cost": "400 "
    },
    {
      "Name": " Roc ",
      "Lvl": "5",
      "Att": "13",
      "Def": "11",
      "minDmg": "11",
      "maxDmg": "15",
      "HP": "60",
      "Spd": "7",
      "Grw": "3",
      "Val": "1027",
      "35 ": "700 ",
      "Special": "Flying",
      "Town": "Stronghold",
      "Cost": "600 "
    },
    {
      "Name": " Thunderbird ",
      "Lvl": "5 up",
      "Att": "13",
      "Def": "11",
      "minDmg": "11",
      "maxDmg": "15",
      "HP": "60",
      "Spd": "11",
      "Grw": "3",
      "Val": "1106",
      "35 ": "750 ",
      "Special": "Flying, Lightning strike",
      "Town": "Stronghold",
      "Cost": "700 "
    },
    {
      "Name": " Cyclops ",
      "Lvl": "6",
      "Att": "15",
      "Def": "12",
      "minDmg": "16",
      "maxDmg": "20",
      "HP": "70",
      "Spd": "6",
      "Grw": "2",
      "Val": "1266",
      "35 ": "1100 ",
      "Special": "Ranged (16 shots), Can attack siege walls",
      "Town": "Stronghold",
      "Cost": "750 "
    },
    {
      "Name": " Cyclops King ",
      "Lvl": "6 up",
      "Att": "17",
      "Def": "13",
      "minDmg": "16",
      "maxDmg": "20",
      "HP": "70",
      "Spd": "8",
      "Grw": "2",
      "Val": "1443",
      "35 ": "1500 ",
      "Special": "Ranged (24 shots), Can attack siege walls",
      "Town": "Stronghold",
      "Cost": "1100 "
    },
    {
      "Name": " Behemoth ",
      "Lvl": "7",
      "Att": "17",
      "Def": "17",
      "minDmg": "30",
      "maxDmg": "50",
      "HP": "160",
      "Spd": "6",
      "Grw": "1",
      "Val": "3162",
      "35 ": "3000 ",
      "Special": "Defense -40% to enemy target",
      "Town": "Stronghold",
      "Cost": "1500 "
    },
    {
      "Name": " Ancient Behemoth ",
      "Lvl": "7 up",
      "Att": "19",
      "Def": "19",
      "minDmg": "30",
      "maxDmg": "50",
      "HP": "300",
      "Spd": "9",
      "Grw": "1",
      "Val": "6168",
      "35 ": "50 ",
      " Special": ", 1  ",
      "Special": "Defense -80% to enemy target",
      "Town": "Stronghold",
      "Cost": "3000 ",
      "SpecialCost": "k1 "
    },
    {
      "Name": " Gnoll ",
      "Lvl": "1",
      "Att": "3",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "6",
      "Spd": "4",
      "Grw": "12",
      "Val": "56",
      "35 ": "70 ",
      "Town": "Fortress",
      "Cost": "50 "
    },
    {
      "Name": " Gnoll Marauder ",
      "Lvl": "1 up",
      "Att": "4",
      "Def": "6",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "6",
      "Spd": "5",
      "Grw": "12",
      "Val": "90",
      "35 ": "110 ",
      "Town": "Fortress",
      "Cost": "70 "
    },
    {
      "Name": " Lizardman ",
      "Lvl": "2",
      "Att": "5",
      "Def": "6",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "14",
      "Spd": "4",
      "Grw": "9",
      "Val": "126",
      "35 ": "140 ",
      "Special": "Ranged (12 shots)",
      "Town": "Fortress",
      "Cost": "110 "
    },
    {
      "Name": " Lizard Warrior ",
      "Lvl": "2 up",
      "Att": "6",
      "Def": "8",
      "minDmg": "2",
      "maxDmg": "5",
      "HP": "15",
      "Spd": "5",
      "Grw": "9",
      "Val": "156",
      "35 ": "220 ",
      "Special": "Ranged (24 shots)",
      "Town": "Fortress",
      "Cost": "140 "
    },
    {
      "Name": " Serpent Fly ",
      "Lvl": "3",
      "Att": "7",
      "Def": "9",
      "minDmg": "2",
      "maxDmg": "5",
      "HP": "20",
      "Spd": "9",
      "Grw": "8",
      "Val": "268",
      "35 ": "240 ",
      "Special": "Flying, Dispel",
      "Town": "Fortress",
      "Cost": "220 "
    },
    {
      "Name": " Dragon Fly ",
      "Lvl": "3 up",
      "Att": "8",
      "Def": "10",
      "minDmg": "2",
      "maxDmg": "5",
      "HP": "20",
      "Spd": "13",
      "Grw": "8",
      "Val": "312",
      "35 ": "325 ",
      "Special": "Flying, Dispel, Weakness",
      "Town": "Fortress",
      "Cost": "240 "
    },
    {
      "Name": " Basilisk ",
      "Lvl": "4",
      "Att": "11",
      "Def": "11",
      "minDmg": "6",
      "maxDmg": "10",
      "HP": "35",
      "Spd": "5",
      "Grw": "4",
      "Val": "552",
      "35 ": "400 ",
      "Special": "Petrify",
      "Town": "Fortress",
      "Cost": "325 "
    },
    {
      "Name": " Greater Basilisk ",
      "Lvl": "4 up",
      "Att": "12",
      "Def": "12",
      "minDmg": "6",
      "maxDmg": "10",
      "HP": "40",
      "Spd": "7",
      "Grw": "4",
      "Val": "714",
      "35 ": "525 ",
      "Special": "Petrify",
      "Town": "Fortress",
      "Cost": "400 "
    },
    {
      "Name": " Gorgon ",
      "Lvl": "5",
      "Att": "10",
      "Def": "14",
      "minDmg": "12",
      "maxDmg": "16",
      "HP": "70",
      "Spd": "5",
      "Grw": "3",
      "Val": "890",
      "35 ": "600 ",
      "Town": "Fortress",
      "Cost": "525 "
    },
    {
      "Name": " Mighty Gorgon ",
      "Lvl": "5 up",
      "Att": "11",
      "Def": "16",
      "minDmg": "12",
      "maxDmg": "16",
      "HP": "70",
      "Spd": "6",
      "Grw": "3",
      "Val": "1028",
      "35 ": "800 ",
      "Special": "Death stare 10% chance/unit",
      "Town": "Fortress",
      "Cost": "600 "
    },
    {
      "Name": " Wyvern ",
      "Lvl": "6",
      "Att": "14",
      "Def": "14",
      "minDmg": "14",
      "maxDmg": "18",
      "HP": "70",
      "Spd": "7",
      "Grw": "2",
      "Val": "1350",
      "35 ": "1100 ",
      "Special": "Flying",
      "Town": "Fortress",
      "Cost": "800 "
    },
    {
      "Name": " Wyvern Monarch ",
      "Lvl": "6 up",
      "Att": "14",
      "Def": "14",
      "minDmg": "18",
      "maxDmg": "22",
      "HP": "70",
      "Spd": "11",
      "Grw": "2",
      "Val": "1518",
      "35 ": "2200 ",
      "Special": "Flying, Poison",
      "Town": "Fortress",
      "Cost": "1100 "
    },
    {
      "Name": " Hydra ",
      "Lvl": "7",
      "Att": "16",
      "Def": "18",
      "minDmg": "25",
      "maxDmg": "45",
      "HP": "175",
      "Spd": "5",
      "Grw": "1",
      "Val": "4120",
      "35 ": "3500 ",
      "Special": "No enemy retaliation, Attack all adjacent enemies",
      "Town": "Fortress",
      "Cost": "2200 "
    },
    {
      "Name": " Chaos Hydra ",
      "Lvl": "7 up",
      "Att": "18",
      "Def": "20",
      "minDmg": "25",
      "maxDmg": "45",
      "HP": "250",
      "Spd": "7",
      "Grw": "1",
      "Val": "5931",
      "35 ": "25 ",
      " Special": ", 1  ",
      "Special": "No enemy retaliation, Attack all adjacent enemies",
      "Town": "Fortress",
      "Cost": "3500 ",
      "SpecialCost": "s1 "
    },
    {
      "Name": " Pixie ",
      "Lvl": "1",
      "Att": "2",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "2",
      "HP": "3",
      "Spd": "7",
      "Grw": "20",
      "Val": "55",
      "35 ": "30 ",
      "Special": "Flying",
      "Town": "Conflux",
      "Cost": "25 "
    },
    {
      "Name": " Sprite ",
      "Lvl": "1 up",
      "Att": "2",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "3",
      "Spd": "9",
      "Grw": "20",
      "Val": "95",
      "35 ": "250 ",
      "Special": "Flying, No enemy retaliation",
      "Town": "Conflux",
      "Cost": "30 "
    },
    {
      "Name": " Air Elemental ",
      "Lvl": "2",
      "Att": "9",
      "Def": "9",
      "minDmg": "2",
      "maxDmg": "8",
      "HP": "25",
      "Spd": "7",
      "Grw": "6",
      "Val": "356",
      "35 ": "275 ",
      "Special": "Elemental, Lightning vulnerability, Immune to Meteor Shower",
      "Town": "Conflux",
      "Cost": "250 "
    },
    {
      "Name": " Storm Elemental ",
      "Lvl": "2 up",
      "Att": "9",
      "Def": "9",
      "minDmg": "2",
      "maxDmg": "8",
      "HP": "25",
      "Spd": "8",
      "Grw": "6",
      "Val": "486",
      "35 ": "300 ",
      "Special": "Ranged (24 shots), Elemental, Lightning vulnerability, Immune to Meteor Shower, CastsProtection from Air",
      "Town": "Conflux",
      "Cost": "275 "
    },
    {
      "Name": " Water Elemental ",
      "Lvl": "3",
      "Att": "8",
      "Def": "10",
      "minDmg": "3",
      "maxDmg": "7",
      "HP": "30",
      "Spd": "5",
      "Grw": "6",
      "Val": "315",
      "35 ": "375 ",
      "Special": "Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon",
      "Town": "Conflux",
      "Cost": "300 "
    },
    {
      "Name": " Ice Elemental ",
      "Lvl": "3 up",
      "Att": "8",
      "Def": "10",
      "minDmg": "3",
      "maxDmg": "7",
      "HP": "30",
      "Spd": "6",
      "Grw": "6",
      "Val": "380",
      "35 ": "350 ",
      "Special": "Ranged (24 shots), Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon, Casts Protection from Water",
      "Town": "Conflux",
      "Cost": "375 "
    },
    {
      "Name": " Fire Elemental ",
      "Lvl": "4",
      "Att": "10",
      "Def": "8",
      "minDmg": "4",
      "maxDmg": "6",
      "HP": "35",
      "Spd": "6",
      "Grw": "5",
      "Val": "345",
      "35 ": "400 ",
      "Special": "Elemental, Ice vulnerability, Fire immunity",
      "Town": "Conflux",
      "Cost": "350 "
    },
    {
      "Name": " Energy Elemental ",
      "Lvl": "4 up",
      "Att": "12",
      "Def": "8",
      "minDmg": "4",
      "maxDmg": "6",
      "HP": "35",
      "Spd": "8",
      "Grw": "5",
      "Val": "470",
      "35 ": "400 ",
      "Special": "Elemental, Flying, Ice vulnerability, Fire immunity, Casts Protection from Fire",
      "Town": "Conflux",
      "Cost": "400 "
    },
    {
      "Name": " Earth Elemental ",
      "Lvl": "5",
      "Att": "10",
      "Def": "10",
      "minDmg": "4",
      "maxDmg": "8",
      "HP": "40",
      "Spd": "4",
      "Grw": "4",
      "Val": "330",
      "35 ": "500 ",
      "Special": "Elemental, Meteor Showervulnerability, Lightning and Armageddon immunity",
      "Town": "Conflux",
      "Cost": "400 "
    },
    {
      "Name": " Magma Elemental ",
      "Lvl": "5 up",
      "Att": "11",
      "Def": "11",
      "minDmg": "6",
      "maxDmg": "10",
      "HP": "40",
      "Spd": "6",
      "Grw": "4",
      "Val": "490",
      "35 ": "950 ",
      "Special": "Elemental, Meteor Showervulnerability, Lightning and Armageddon immunity, Casts Protection from Earth",
      "Town": "Conflux",
      "Cost": "500 "
    },
    {
      "Name": " Psychic Elemental ",
      "Lvl": "6",
      "Att": "15",
      "Def": "13",
      "minDmg": "10",
      "maxDmg": "20",
      "HP": "75",
      "Spd": "7",
      "Grw": "2",
      "Val": "1669",
      "35 ": "1200 ",
      "Special": "Elemental, No enemy retaliation, Attacks adjacent hexes",
      "Town": "Conflux",
      "Cost": "950 "
    },
    {
      "Name": " Magic Elemental ",
      "Lvl": "6 up",
      "Att": "15",
      "Def": "13",
      "minDmg": "15",
      "maxDmg": "25",
      "HP": "80",
      "Spd": "9",
      "Grw": "2",
      "Val": "2012",
      "35 ": "2000 ",
      "Special": "Elemental, No enemy retaliation, Attacks adjacent hexes, Spell immunity",
      "Town": "Conflux",
      "Cost": "1200 "
    },
    {
      "Name": " Firebird ",
      "Lvl": "7",
      "Att": "18",
      "Def": "18",
      "minDmg": "30",
      "maxDmg": "40",
      "HP": "150",
      "Spd": "15",
      "Grw": "1",
      "Val": "4336",
      "35 ": "3000 ",
      "Special": "Flying, Breath attack, 50% fire resistance",
      "Town": "Conflux",
      "Cost": "2000 "
    },
    {
      "Name": " Phoenix ",
      "Lvl": "7 up",
      "Att": "21",
      "Def": "18",
      "minDmg": "30",
      "maxDmg": "40",
      "HP": "200",
      "Spd": "21",
      "Grw": "1",
      "Val": "6721",
      "35 ": "10 ",
      " Special": ", 1  ",
      "Special": "Flying, Breath attack, Immune to fire spells, Rebirth",
      "Town": "Conflux",
      "Cost": "3000 ",
      "SpecialCost": "m1"
    },
    {
      "Name": " Peasant ",
      "Lvl": "1",
      "Att": "1",
      "Def": "1",
      "minDmg": "1",
      "maxDmg": "1",
      "HP": "1",
      "Spd": "3",
      "Grw": "25",
      "Val": "15",
      "35 ": "40 ",
      "Town": "Neutral",
      "Cost": "10 "
    },
    {
      "Name": " Halfling ",
      "Lvl": "1",
      "Att": "4",
      "Def": "2",
      "minDmg": "1",
      "maxDmg": "3",
      "HP": "4",
      "Spd": "5",
      "Grw": "15",
      "Val": "75",
      "35 ": "150 ",
      "Special": "Ranged (24 shots), Positive Luck",
      "Town": "Neutral",
      "Cost": "40 "
    },
    {
      "Name": " Boar ",
      "Lvl": "2",
      "Att": "6",
      "Def": "5",
      "minDmg": "2",
      "maxDmg": "3",
      "HP": "15",
      "Spd": "6",
      "Grw": "8",
      "Val": "145",
      "35 ": "100 ",
      "Town": "Neutral",
      "Cost": "150 "
    },
    {
      "Name": " Rogue ",
      "Lvl": "2",
      "Att": "8",
      "Def": "3",
      "minDmg": "2",
      "maxDmg": "4",
      "HP": "10",
      "Spd": "6",
      "Grw": "8",
      "Val": "135",
      "35 ": "100 ",
      "Special": "Spying",
      "Town": "Neutral",
      "Cost": "100 "
    },
    {
      "Name": " Leprechaun ",
      "Lvl": "2",
      "Att": "8",
      "Def": "5",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "15",
      "Spd": "5",
      "Grw": "9",
      "Val": "208",
      "35 ": "300 ",
      "Special": "Doubles friendly unit Luckchance, Casts Fortune",
      "Town": "Neutral",
      "Cost": "100 "
    },
    {
      "Name": " Mummy ",
      "Lvl": "3",
      "Att": "7",
      "Def": "7",
      "minDmg": "3",
      "maxDmg": "5",
      "HP": "30",
      "Spd": "5",
      "Grw": "7",
      "Val": "270",
      "35 ": "200 ",
      "Special": "Undead, Curse",
      "Town": "Neutral",
      "Cost": "300 "
    },
    {
      "Name": " Nomad ",
      "Lvl": "3",
      "Att": "9",
      "Def": "8",
      "minDmg": "2",
      "maxDmg": "6",
      "HP": "30",
      "Spd": "7",
      "Grw": "7",
      "Val": "345",
      "35 ": "400 ",
      "Special": "Sandwalker",
      "Town": "Neutral",
      "Cost": "200 "
    },
    {
      "Name": " Sharpshooter ",
      "Lvl": "4",
      "Att": "12",
      "Def": "10",
      "minDmg": "8",
      "maxDmg": "10",
      "HP": "15",
      "Spd": "9",
      "Grw": "4",
      "Val": "585",
      "35 ": "300 ",
      "Special": "Ranged (32 shots), No range and obstacle penalty",
      "Town": "Neutral",
      "Cost": "400 "
    },
    {
      "Name": " Satyr ",
      "Lvl": "4",
      "Att": "10",
      "Def": "11",
      "minDmg": "6",
      "maxDmg": "10",
      "HP": "35",
      "Spd": "7",
      "Grw": "4",
      "Val": "518",
      "35 ": "400 ",
      "Special": "Casts Mirth",
      "Town": "Neutral",
      "Cost": "300 "
    },
    {
      "Name": " Steel Golem ",
      "Lvl": "4",
      "Att": "10",
      "Def": "11",
      "minDmg": "6",
      "maxDmg": "8",
      "HP": "45",
      "Spd": "6",
      "Grw": "4",
      "Val": "597",
      "35 ": "500 ",
      "Special": "Unliving, Spell Damage Resistance +80%",
      "Town": "Neutral",
      "Cost": "400 "
    },
    {
      "Name": " Troll ",
      "Lvl": "5",
      "Att": "14",
      "Def": "7",
      "minDmg": "10",
      "maxDmg": "15",
      "HP": "40",
      "Spd": "7",
      "Grw": "3",
      "Val": "1024",
      "35 ": "500 ",
      "Special": "Regeneration",
      "Town": "Neutral",
      "Cost": "500 "
    },
    {
      "Name": " Gold Golem ",
      "Lvl": "5",
      "Att": "11",
      "Def": "12",
      "minDmg": "8",
      "maxDmg": "10",
      "HP": "50",
      "Spd": "5",
      "Grw": "3",
      "Val": "600",
      "35 ": "600 ",
      "Special": "Unliving, Spell Damage Resistance +85%",
      "Town": "Neutral",
      "Cost": "500 "
    },
    {
      "Name": " Fangarm ",
      "Lvl": "5",
      "Att": "12",
      "Def": "12",
      "minDmg": "8",
      "maxDmg": "12",
      "HP": "50",
      "Spd": "6",
      "Grw": "3",
      "Val": "929",
      "35 ": "750 ",
      "Special": "Flying, Mind spellimmunity, Unlimited retaliations, Casts Hypnotize on attacked stack",
      "Town": "Neutral",
      "Cost": "600 "
    },
    {
      "Name": " Diamond Golem ",
      "Lvl": "6",
      "Att": "13",
      "Def": "12",
      "minDmg": "10",
      "maxDmg": "14",
      "HP": "60",
      "Spd": "5",
      "Grw": "2",
      "Val": "775",
      "35 ": "750 ",
      "Special": "Unliving, Spell Damage Resistance +95%",
      "Town": "Neutral",
      "Cost": "750 "
    },
    {
      "Name": " Enchanter ",
      "Lvl": "6",
      "Att": "17",
      "Def": "12",
      "minDmg": "14",
      "maxDmg": "14",
      "HP": "30",
      "Spd": "9",
      "Grw": "2",
      "Val": "1210",
      "35 ": "10000 ",
      "Special": "Ranged (32 shots), No melee and obstacle penalty, Spellcaster",
      "Town": "Neutral",
      "Cost": "750 "
    },
    {
      "Name": " Faerie Dragon ",
      "Lvl": "7",
      "Att": "20",
      "Def": "20",
      "minDmg": "20",
      "maxDmg": "30",
      "HP": "500",
      "Spd": "15",
      "Grw": "1",
      "Val": "30501",
      "35 ": "15000 ",
      " Special": ", 8  ",
      "Special": "Dragon, Flying, Spellcaster, Magic Mirror",
      "Town": "Neutral",
      "Cost": "10000 ",
      "SpecialCost": "g8"
    },
    {
      "Name": " Rust Dragon ",
      "Lvl": "7",
      "Att": "30",
      "Def": "30",
      "minDmg": "50",
      "maxDmg": "50",
      "HP": "750",
      "Spd": "17",
      "Grw": "1",
      "Val": "26433",
      "35 ": "20000 ",
      " Special": ",14  ",
      "Special": "Dragon, Flying, Breath, Acid breath",
      "Town": "Neutral",
      "Cost": "15000 ",
      "SpecialCost": "s14"
    },
    {
      "Name": " Crystal Dragon ",
      "Lvl": "7",
      "Att": "40",
      "Def": "40",
      "minDmg": "60",
      "maxDmg": "75",
      "HP": "800",
      "Spd": "16",
      "Grw": "1",
      "Val": "39338",
      "35 ": "30000 ",
      " Special": ",10  ",
      "Special": "Dragon, Crystal generation, Magic resistance +20%",
      "Town": "Neutral",
      "Cost": "20000 ",
      "SpecialCost": "k10"
    },
    {
      "Name": " Azure Dragon ",
      "Lvl": "7",
      "Att": "50",
      "Def": "50",
      "minDmg": "70",
      "maxDmg": "80",
      "HP": "1000",
      "Spd": "19",
      "Grw": "1",
      "Val": "78845",
      " Special": ",20  ",
      "Special": "Dragon, Flying, Breath, Fear, Resist lvl 1–3 spells, Resist Fear",
      "Town": "Neutral",
      "Cost": "30000 ",
      "SpecialCost": "m20"
    }
  ]


  constructor() { }

  getCreaturesFromTown(town) {
    return this.creatures.filter(x => x.Town == town);
  }

  getSelectedCreature(creature) {
    return this.creatures.find(x => x.Name == creature);
  }

  getAllCreatures() {
    return this.creatures;
  }

  SearchCreatures(name) {
    return this.creatures.filter(x => x.Name )
  }




}
